// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvBUnAyauh_0NLqoPCD9NcqxQMOC6Y9c',
    appId: '1:642428874440:web:b3fbff98d959201b243ffd',
    messagingSenderId: '642428874440',
    projectId: 'chat-b47a7',
    authDomain: 'chat-b47a7.firebaseapp.com',
    storageBucket: 'chat-b47a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAayVuXbK3WFF2rMYC9MHRUihztiJbZz8w',
    appId: '1:642428874440:android:02e16914bde01377243ffd',
    messagingSenderId: '642428874440',
    projectId: 'chat-b47a7',
    storageBucket: 'chat-b47a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6Re2_RYcxkO0M6jim7UUmPX4elJjwas',
    appId: '1:642428874440:ios:0d632db4a5c3b2ec243ffd',
    messagingSenderId: '642428874440',
    projectId: 'chat-b47a7',
    storageBucket: 'chat-b47a7.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6Re2_RYcxkO0M6jim7UUmPX4elJjwas',
    appId: '1:642428874440:ios:0d632db4a5c3b2ec243ffd',
    messagingSenderId: '642428874440',
    projectId: 'chat-b47a7',
    storageBucket: 'chat-b47a7.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFvBUnAyauh_0NLqoPCD9NcqxQMOC6Y9c',
    appId: '1:642428874440:web:6f35a7f6ecbe5758243ffd',
    messagingSenderId: '642428874440',
    projectId: 'chat-b47a7',
    authDomain: 'chat-b47a7.firebaseapp.com',
    storageBucket: 'chat-b47a7.appspot.com',
  );
}
